// Copyright 2026 SoundMesh. All rights reserved.
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.soundmesh.soundmesh

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object SoundMeshMessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionState (
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionState {
      val state = pigeonVar_list[0] as String
      return ConnectionState(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionState
    return SoundMeshMessagesPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "ConnectionState(state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeviceInfo (
  val platformName: String,
  val osVersion: String,
  val deviceModel: String,
  val brand: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfo {
      val platformName = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String
      val deviceModel = pigeonVar_list[2] as String
      val brand = pigeonVar_list[3] as String?
      return DeviceInfo(platformName, osVersion, deviceModel, brand)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platformName,
      osVersion,
      deviceModel,
      brand,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceInfo
    return SoundMeshMessagesPigeonUtils.deepEquals(this.platformName, other.platformName) && SoundMeshMessagesPigeonUtils.deepEquals(this.osVersion, other.osVersion) && SoundMeshMessagesPigeonUtils.deepEquals(this.deviceModel, other.deviceModel) && SoundMeshMessagesPigeonUtils.deepEquals(this.brand, other.brand)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.platformName)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.osVersion)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.deviceModel)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.brand)
    return result
  }
  override fun toString(): String {
    return "DeviceInfo(platformName=$platformName, osVersion=$osVersion, deviceModel=$deviceModel, brand=$brand)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureState (
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureState {
      val state = pigeonVar_list[0] as String
      return CaptureState(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureState
    return SoundMeshMessagesPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "CaptureState(state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureMetadata (
  val sessionId: String,
  val generation: Long,
  val sampleRate: Long,
  val channelCount: Long,
  val startedAtNanos: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureMetadata {
      val sessionId = pigeonVar_list[0] as String
      val generation = pigeonVar_list[1] as Long
      val sampleRate = pigeonVar_list[2] as Long
      val channelCount = pigeonVar_list[3] as Long
      val startedAtNanos = pigeonVar_list[4] as Long
      return CaptureMetadata(sessionId, generation, sampleRate, channelCount, startedAtNanos)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      generation,
      sampleRate,
      channelCount,
      startedAtNanos,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureMetadata
    return SoundMeshMessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && SoundMeshMessagesPigeonUtils.deepEquals(this.generation, other.generation) && SoundMeshMessagesPigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && SoundMeshMessagesPigeonUtils.deepEquals(this.channelCount, other.channelCount) && SoundMeshMessagesPigeonUtils.deepEquals(this.startedAtNanos, other.startedAtNanos)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.generation)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.channelCount)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.startedAtNanos)
    return result
  }
  override fun toString(): String {
    return "CaptureMetadata(sessionId=$sessionId, generation=$generation, sampleRate=$sampleRate, channelCount=$channelCount, startedAtNanos=$startedAtNanos)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureError (
  val code: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return CaptureError(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureError
    return SoundMeshMessagesPigeonUtils.deepEquals(this.code, other.code) && SoundMeshMessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "CaptureError(code=$code, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CapturePermissionResult (
  val result: String,
  val error: CaptureError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CapturePermissionResult {
      val result = pigeonVar_list[0] as String
      val error = pigeonVar_list[1] as CaptureError?
      return CapturePermissionResult(result, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      result,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CapturePermissionResult
    return SoundMeshMessagesPigeonUtils.deepEquals(this.result, other.result) && SoundMeshMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.result)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "CapturePermissionResult(result=$result, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureResult (
  val success: Boolean,
  val metadata: CaptureMetadata? = null,
  val error: CaptureError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureResult {
      val success = pigeonVar_list[0] as Boolean
      val metadata = pigeonVar_list[1] as CaptureMetadata?
      val error = pigeonVar_list[2] as CaptureError?
      return CaptureResult(success, metadata, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      metadata,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureResult
    return SoundMeshMessagesPigeonUtils.deepEquals(this.success, other.success) && SoundMeshMessagesPigeonUtils.deepEquals(this.metadata, other.metadata) && SoundMeshMessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.success)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.metadata)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "CaptureResult(success=$success, metadata=$metadata, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureStateResult (
  val state: CaptureState,
  val metadata: CaptureMetadata? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureStateResult {
      val state = pigeonVar_list[0] as CaptureState
      val metadata = pigeonVar_list[1] as CaptureMetadata?
      return CaptureStateResult(state, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      metadata,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureStateResult
    return SoundMeshMessagesPigeonUtils.deepEquals(this.state, other.state) && SoundMeshMessagesPigeonUtils.deepEquals(this.metadata, other.metadata)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.metadata)
    return result
  }
  override fun toString(): String {
    return "CaptureStateResult(state=$state, metadata=$metadata)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FrameArrivalStats (
  val totalFrames: Long,
  val totalBytes: Long,
  val silentFrames: Long,
  val framesPerSecond: Long,
  val bytesPerSecond: Long,
  val timestampNanos: Long,
  val isReceivingAudio: Boolean,
  val peakAmplitude: Long,
  val isSilent: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameArrivalStats {
      val totalFrames = pigeonVar_list[0] as Long
      val totalBytes = pigeonVar_list[1] as Long
      val silentFrames = pigeonVar_list[2] as Long
      val framesPerSecond = pigeonVar_list[3] as Long
      val bytesPerSecond = pigeonVar_list[4] as Long
      val timestampNanos = pigeonVar_list[5] as Long
      val isReceivingAudio = pigeonVar_list[6] as Boolean
      val peakAmplitude = pigeonVar_list[7] as Long
      val isSilent = pigeonVar_list[8] as Boolean
      return FrameArrivalStats(totalFrames, totalBytes, silentFrames, framesPerSecond, bytesPerSecond, timestampNanos, isReceivingAudio, peakAmplitude, isSilent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalFrames,
      totalBytes,
      silentFrames,
      framesPerSecond,
      bytesPerSecond,
      timestampNanos,
      isReceivingAudio,
      peakAmplitude,
      isSilent,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FrameArrivalStats
    return SoundMeshMessagesPigeonUtils.deepEquals(this.totalFrames, other.totalFrames) && SoundMeshMessagesPigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && SoundMeshMessagesPigeonUtils.deepEquals(this.silentFrames, other.silentFrames) && SoundMeshMessagesPigeonUtils.deepEquals(this.framesPerSecond, other.framesPerSecond) && SoundMeshMessagesPigeonUtils.deepEquals(this.bytesPerSecond, other.bytesPerSecond) && SoundMeshMessagesPigeonUtils.deepEquals(this.timestampNanos, other.timestampNanos) && SoundMeshMessagesPigeonUtils.deepEquals(this.isReceivingAudio, other.isReceivingAudio) && SoundMeshMessagesPigeonUtils.deepEquals(this.peakAmplitude, other.peakAmplitude) && SoundMeshMessagesPigeonUtils.deepEquals(this.isSilent, other.isSilent)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.totalFrames)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.silentFrames)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.framesPerSecond)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.bytesPerSecond)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.timestampNanos)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.isReceivingAudio)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.peakAmplitude)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.isSilent)
    return result
  }
  override fun toString(): String {
    return "FrameArrivalStats(totalFrames=$totalFrames, totalBytes=$totalBytes, silentFrames=$silentFrames, framesPerSecond=$framesPerSecond, bytesPerSecond=$bytesPerSecond, timestampNanos=$timestampNanos, isReceivingAudio=$isReceivingAudio, peakAmplitude=$peakAmplitude, isSilent=$isSilent)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StreamingMetadata (
  val sessionId: String,
  val generation: Long,
  val sampleRate: Long,
  val channelCount: Long,
  val startedAtNanos: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamingMetadata {
      val sessionId = pigeonVar_list[0] as String
      val generation = pigeonVar_list[1] as Long
      val sampleRate = pigeonVar_list[2] as Long
      val channelCount = pigeonVar_list[3] as Long
      val startedAtNanos = pigeonVar_list[4] as Long
      return StreamingMetadata(sessionId, generation, sampleRate, channelCount, startedAtNanos)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      generation,
      sampleRate,
      channelCount,
      startedAtNanos,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StreamingMetadata
    return SoundMeshMessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && SoundMeshMessagesPigeonUtils.deepEquals(this.generation, other.generation) && SoundMeshMessagesPigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && SoundMeshMessagesPigeonUtils.deepEquals(this.channelCount, other.channelCount) && SoundMeshMessagesPigeonUtils.deepEquals(this.startedAtNanos, other.startedAtNanos)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.generation)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.channelCount)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.startedAtNanos)
    return result
  }
  override fun toString(): String {
    return "StreamingMetadata(sessionId=$sessionId, generation=$generation, sampleRate=$sampleRate, channelCount=$channelCount, startedAtNanos=$startedAtNanos)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StreamingState (
  val state: String,
  val metadata: StreamingMetadata? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamingState {
      val state = pigeonVar_list[0] as String
      val metadata = pigeonVar_list[1] as StreamingMetadata?
      return StreamingState(state, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      metadata,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StreamingState
    return SoundMeshMessagesPigeonUtils.deepEquals(this.state, other.state) && SoundMeshMessagesPigeonUtils.deepEquals(this.metadata, other.metadata)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.metadata)
    return result
  }
  override fun toString(): String {
    return "StreamingState(state=$state, metadata=$metadata)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiveStats (
  val packetsReceived: Long,
  val packetsLost: Long,
  val packetsOutOfOrder: Long,
  val bufferDepthMs: Long,
  val lossRate: Double,
  val timestampNanos: Long,
  val isHealthy: Boolean,
  val peakAmplitude: Long,
  val isSilent: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReceiveStats {
      val packetsReceived = pigeonVar_list[0] as Long
      val packetsLost = pigeonVar_list[1] as Long
      val packetsOutOfOrder = pigeonVar_list[2] as Long
      val bufferDepthMs = pigeonVar_list[3] as Long
      val lossRate = pigeonVar_list[4] as Double
      val timestampNanos = pigeonVar_list[5] as Long
      val isHealthy = pigeonVar_list[6] as Boolean
      val peakAmplitude = pigeonVar_list[7] as Long
      val isSilent = pigeonVar_list[8] as Boolean
      return ReceiveStats(packetsReceived, packetsLost, packetsOutOfOrder, bufferDepthMs, lossRate, timestampNanos, isHealthy, peakAmplitude, isSilent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packetsReceived,
      packetsLost,
      packetsOutOfOrder,
      bufferDepthMs,
      lossRate,
      timestampNanos,
      isHealthy,
      peakAmplitude,
      isSilent,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ReceiveStats
    return SoundMeshMessagesPigeonUtils.deepEquals(this.packetsReceived, other.packetsReceived) && SoundMeshMessagesPigeonUtils.deepEquals(this.packetsLost, other.packetsLost) && SoundMeshMessagesPigeonUtils.deepEquals(this.packetsOutOfOrder, other.packetsOutOfOrder) && SoundMeshMessagesPigeonUtils.deepEquals(this.bufferDepthMs, other.bufferDepthMs) && SoundMeshMessagesPigeonUtils.deepEquals(this.lossRate, other.lossRate) && SoundMeshMessagesPigeonUtils.deepEquals(this.timestampNanos, other.timestampNanos) && SoundMeshMessagesPigeonUtils.deepEquals(this.isHealthy, other.isHealthy) && SoundMeshMessagesPigeonUtils.deepEquals(this.peakAmplitude, other.peakAmplitude) && SoundMeshMessagesPigeonUtils.deepEquals(this.isSilent, other.isSilent)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.packetsReceived)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.packetsLost)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.packetsOutOfOrder)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.bufferDepthMs)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.lossRate)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.timestampNanos)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.isHealthy)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.peakAmplitude)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.isSilent)
    return result
  }
  override fun toString(): String {
    return "ReceiveStats(packetsReceived=$packetsReceived, packetsLost=$packetsLost, packetsOutOfOrder=$packetsOutOfOrder, bufferDepthMs=$bufferDepthMs, lossRate=$lossRate, timestampNanos=$timestampNanos, isHealthy=$isHealthy, peakAmplitude=$peakAmplitude, isSilent=$isSilent)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiveState (
  val state: String,
  val stats: ReceiveStats? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReceiveState {
      val state = pigeonVar_list[0] as String
      val stats = pigeonVar_list[1] as ReceiveStats?
      return ReceiveState(state, stats)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      stats,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ReceiveState
    return SoundMeshMessagesPigeonUtils.deepEquals(this.state, other.state) && SoundMeshMessagesPigeonUtils.deepEquals(this.stats, other.stats)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.stats)
    return result
  }
  override fun toString(): String {
    return "ReceiveState(state=$state, stats=$stats)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OutputState (
  val state: String,
  val bufferedMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OutputState {
      val state = pigeonVar_list[0] as String
      val bufferedMs = pigeonVar_list[1] as Long
      return OutputState(state, bufferedMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      bufferedMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OutputState
    return SoundMeshMessagesPigeonUtils.deepEquals(this.state, other.state) && SoundMeshMessagesPigeonUtils.deepEquals(this.bufferedMs, other.bufferedMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.bufferedMs)
    return result
  }
  override fun toString(): String {
    return "OutputState(state=$state, bufferedMs=$bufferedMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OutputError (
  val code: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OutputError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return OutputError(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OutputError
    return SoundMeshMessagesPigeonUtils.deepEquals(this.code, other.code) && SoundMeshMessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "OutputError(code=$code, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScheduleResult (
  val success: Boolean,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScheduleResult {
      val success = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as String?
      val errorMessage = pigeonVar_list[2] as String?
      return ScheduleResult(success, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScheduleResult
    return SoundMeshMessagesPigeonUtils.deepEquals(this.success, other.success) && SoundMeshMessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && SoundMeshMessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.success)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "ScheduleResult(success=$success, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NextFrameInfo (
  val framePosition: Long,
  val sequenceNumber: Long,
  val generation: Long,
  val sampleRate: Long,
  val channelCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NextFrameInfo {
      val framePosition = pigeonVar_list[0] as Long
      val sequenceNumber = pigeonVar_list[1] as Long
      val generation = pigeonVar_list[2] as Long
      val sampleRate = pigeonVar_list[3] as Long
      val channelCount = pigeonVar_list[4] as Long
      return NextFrameInfo(framePosition, sequenceNumber, generation, sampleRate, channelCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      framePosition,
      sequenceNumber,
      generation,
      sampleRate,
      channelCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NextFrameInfo
    return SoundMeshMessagesPigeonUtils.deepEquals(this.framePosition, other.framePosition) && SoundMeshMessagesPigeonUtils.deepEquals(this.sequenceNumber, other.sequenceNumber) && SoundMeshMessagesPigeonUtils.deepEquals(this.generation, other.generation) && SoundMeshMessagesPigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && SoundMeshMessagesPigeonUtils.deepEquals(this.channelCount, other.channelCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.framePosition)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sequenceNumber)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.generation)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.channelCount)
    return result
  }
  override fun toString(): String {
    return "NextFrameInfo(framePosition=$framePosition, sequenceNumber=$sequenceNumber, generation=$generation, sampleRate=$sampleRate, channelCount=$channelCount)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PipelineError (
  val code: String,
  val message: String,
  val generation: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PipelineError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val generation = pigeonVar_list[2] as Long
      return PipelineError(code, message, generation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      generation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PipelineError
    return SoundMeshMessagesPigeonUtils.deepEquals(this.code, other.code) && SoundMeshMessagesPigeonUtils.deepEquals(this.message, other.message) && SoundMeshMessagesPigeonUtils.deepEquals(this.generation, other.generation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.generation)
    return result
  }
  override fun toString(): String {
    return "PipelineError(code=$code, message=$message, generation=$generation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TimeSyncResponse (
  val t1: Long,
  val t2: Long,
  val t3: Long,
  val generation: Long,
  val sessionId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TimeSyncResponse {
      val t1 = pigeonVar_list[0] as Long
      val t2 = pigeonVar_list[1] as Long
      val t3 = pigeonVar_list[2] as Long
      val generation = pigeonVar_list[3] as Long
      val sessionId = pigeonVar_list[4] as String
      return TimeSyncResponse(t1, t2, t3, generation, sessionId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      t1,
      t2,
      t3,
      generation,
      sessionId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TimeSyncResponse
    return SoundMeshMessagesPigeonUtils.deepEquals(this.t1, other.t1) && SoundMeshMessagesPigeonUtils.deepEquals(this.t2, other.t2) && SoundMeshMessagesPigeonUtils.deepEquals(this.t3, other.t3) && SoundMeshMessagesPigeonUtils.deepEquals(this.generation, other.generation) && SoundMeshMessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.t1)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.t2)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.t3)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.generation)
    result = 31 * result + SoundMeshMessagesPigeonUtils.deepHash(this.sessionId)
    return result
  }
  override fun toString(): String {
    return "TimeSyncResponse(t1=$t1, t2=$t2, t3=$t3, generation=$generation, sessionId=$sessionId)"
  }
}
private open class SoundMeshMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionState.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureState.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureMetadata.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureError.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CapturePermissionResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureStateResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameArrivalStats.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamingMetadata.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamingState.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReceiveStats.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReceiveState.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OutputState.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OutputError.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScheduleResult.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NextFrameInfo.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PipelineError.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TimeSyncResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnectionState -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DeviceInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CaptureState -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CaptureMetadata -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CaptureError -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CapturePermissionResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CaptureResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CaptureStateResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is FrameArrivalStats -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is StreamingMetadata -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is StreamingState -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is ReceiveStats -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ReceiveState -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is OutputState -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is OutputError -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is ScheduleResult -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is NextFrameInfo -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is PipelineError -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is TimeSyncResponse -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AudioOutputPlatform {
  fun getOutputState(): OutputState
  fun scheduleFrame(framePosition: Long, targetNativeTimeNanos: Long, generation: Long): ScheduleResult

  companion object {
    /** The codec used by AudioOutputPlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `AudioOutputPlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioOutputPlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioOutputPlatform.getOutputState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getOutputState())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioOutputPlatform.scheduleFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val framePositionArg = args[0] as Long
            val targetNativeTimeNanosArg = args[1] as Long
            val generationArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.scheduleFrame(framePositionArg, targetNativeTimeNanosArg, generationArg))
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AudioOutputFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AudioOutputFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
  }
  suspend fun onOutputStateChanged(stateArg: String, bufferedMsArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.onOutputStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg, bufferedMsArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onOutputError(errorCodeArg: String, errorMessageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.onOutputError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(errorCodeArg, errorMessageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun requestScheduleTarget(framePositionArg: Long, captureTimestampNsArg: Long, generationArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.requestScheduleTarget$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(framePositionArg, captureTimestampNsArg, generationArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NetworkHostPlatform {
  fun startHosting(port: Long): Boolean
  fun connectToHost(ipAddress: String, port: Long): Boolean
  fun sendMessage(message: String): Boolean
  fun sendChatMessage(text: String): Boolean
  fun sendProtocolMessage(message: String): Boolean
  fun disconnect()
  fun getLocalIpAddress(): String
  suspend fun setHeartbeatConfig(intervalMs: Long, timeoutMs: Long)
  suspend fun reconnectToHost(ipAddress: String, port: Long): Boolean

  companion object {
    /** The codec used by NetworkHostPlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `NetworkHostPlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NetworkHostPlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.startHosting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val portArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.startHosting(portArg))
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.connectToHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ipAddressArg = args[0] as String
            val portArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.connectToHost(ipAddressArg, portArg))
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.sendMessage(messageArg))
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendChatMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.sendChatMessage(textArg))
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendProtocolMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.sendProtocolMessage(messageArg))
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnect()
              listOf(null)
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.getLocalIpAddress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLocalIpAddress())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.setHeartbeatConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val intervalMsArg = args[0] as Long
            val timeoutMsArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setHeartbeatConfig(intervalMsArg, timeoutMsArg)
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.reconnectToHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ipAddressArg = args[0] as String
            val portArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.reconnectToHost(ipAddressArg, portArg))
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DevicePlatform {
  fun getDeviceInfo(): DeviceInfo

  companion object {
    /** The codec used by DevicePlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `DevicePlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DevicePlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.DevicePlatform.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceInfo())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TimingPlatform {
  fun getMonotonicTimeNanos(): Long

  companion object {
    /** The codec used by TimingPlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `TimingPlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TimingPlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.TimingPlatform.getMonotonicTimeNanos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getMonotonicTimeNanos())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AudioCapturePlatform {
  suspend fun requestCapturePermission(): CapturePermissionResult
  suspend fun startCapture(): CaptureResult
  suspend fun stopCapture()
  fun getCaptureState(): CaptureStateResult
  fun isIgnoringBatteryOptimizations(): Boolean
  suspend fun requestIgnoreBatteryOptimizations()
  suspend fun startStreaming()
  suspend fun stopStreaming()
  fun getStreamingState(): StreamingState

  companion object {
    /** The codec used by AudioCapturePlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `AudioCapturePlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioCapturePlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.requestCapturePermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestCapturePermission())
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.startCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startCapture())
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.stopCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopCapture()
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.getCaptureState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCaptureState())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.isIgnoringBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isIgnoringBatteryOptimizations())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.requestIgnoreBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.requestIgnoreBatteryOptimizations()
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.startStreaming$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.startStreaming()
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.stopStreaming$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopStreaming()
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.getStreamingState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStreamingState())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AudioReceivePlatform {
  fun getReceiveState(): ReceiveState
  fun getNextFrameInfo(): NextFrameInfo?

  companion object {
    /** The codec used by AudioReceivePlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `AudioReceivePlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioReceivePlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioReceivePlatform.getReceiveState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getReceiveState())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.AudioReceivePlatform.getNextFrameInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNextFrameInfo())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NetworkFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NetworkFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
  }
  suspend fun onMessageReceived(messageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onMessageReceived$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(messageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onConnectionStateChanged(stateArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onConnectionError(errorCodeArg: String, errorMessageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(errorCodeArg, errorMessageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AudioCaptureFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AudioCaptureFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
  }
  suspend fun onCaptureStateChanged(stateArg: String, metadataArg: CaptureMetadata?)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg, metadataArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onCaptureError(errorCodeArg: String, errorMessageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(errorCodeArg, errorMessageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onCaptureFramesReceived(statsArg: FrameArrivalStats)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureFramesReceived$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(statsArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onStreamStateChanged(stateArg: String, metadataArg: StreamingMetadata?)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onStreamStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg, metadataArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onStreamError(errorCodeArg: String, errorMessageArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onStreamError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(errorCodeArg, errorMessageArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AudioReceiveFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AudioReceiveFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
  }
  suspend fun onStreamStateChanged(stateArg: String, statsArg: ReceiveStats?)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioReceiveFlutterApi.onStreamStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg, statsArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onAudioLevelUpdate(peakAmplitudeArg: Long, isSilentArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.AudioReceiveFlutterApi.onAudioLevelUpdate$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(peakAmplitudeArg, isSilentArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PipelineFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PipelineFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
  }
  suspend fun onPipelineStateChanged(stateArg: String, generationArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onPipelineStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg, generationArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onPipelineError(errorArg: PipelineError)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onPipelineError$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(errorArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onTimeSyncResponse(responseArg: TimeSyncResponse)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onTimeSyncResponse$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(responseArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onSyncStateChanged(stateArg: String, generationArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onSyncStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(stateArg, generationArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(SoundMeshMessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PipelinePlatform {
  suspend fun startPipeline()
  suspend fun stopPipeline()
  fun getPipelineGeneration(): Long
  fun getPipelineState(): String
  fun getSyncState(): String
  fun updateSyncState(state: String, generation: Long)

  companion object {
    /** The codec used by PipelinePlatform. */
    val codec: MessageCodec<Any?> by lazy {
      SoundMeshMessagesPigeonCodec()
    }
    /** Sets up an instance of `PipelinePlatform` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PipelinePlatform?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.PipelinePlatform.startPipeline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.startPipeline()
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.PipelinePlatform.stopPipeline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopPipeline()
                listOf(null)
              } catch (exception: Throwable) {
                SoundMeshMessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.PipelinePlatform.getPipelineGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPipelineGeneration())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.PipelinePlatform.getPipelineState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPipelineState())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.PipelinePlatform.getSyncState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSyncState())
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.soundmesh.PipelinePlatform.updateSyncState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as String
            val generationArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.updateSyncState(stateArg, generationArg)
              listOf(null)
            } catch (exception: Throwable) {
              SoundMeshMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
