// Copyright 2026 SoundMesh. All rights reserved.
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class ConnectionState {
  ConnectionState({
    required this.state,
  });

  String state;

  List<Object?> _toList() {
    return <Object?>[
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectionState decode(Object result) {
    result as List<Object?>;
    return ConnectionState(
      state: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConnectionState(state: $state)';
  }
}

class DeviceInfo {
  DeviceInfo({
    required this.platformName,
    required this.osVersion,
    required this.deviceModel,
    this.brand,
  });

  String platformName;

  String osVersion;

  String deviceModel;

  String? brand;

  List<Object?> _toList() {
    return <Object?>[
      platformName,
      osVersion,
      deviceModel,
      brand,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceInfo decode(Object result) {
    result as List<Object?>;
    return DeviceInfo(
      platformName: result[0]! as String,
      osVersion: result[1]! as String,
      deviceModel: result[2]! as String,
      brand: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(platformName, other.platformName) && _deepEquals(osVersion, other.osVersion) && _deepEquals(deviceModel, other.deviceModel) && _deepEquals(brand, other.brand);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceInfo(platformName: $platformName, osVersion: $osVersion, deviceModel: $deviceModel, brand: $brand)';
  }
}

class CaptureState {
  CaptureState({
    required this.state,
  });

  String state;

  List<Object?> _toList() {
    return <Object?>[
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureState decode(Object result) {
    result as List<Object?>;
    return CaptureState(
      state: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureState(state: $state)';
  }
}

class CaptureMetadata {
  CaptureMetadata({
    required this.sessionId,
    required this.generation,
    required this.sampleRate,
    required this.channelCount,
    required this.startedAtNanos,
  });

  String sessionId;

  int generation;

  int sampleRate;

  int channelCount;

  int startedAtNanos;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      generation,
      sampleRate,
      channelCount,
      startedAtNanos,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureMetadata decode(Object result) {
    result as List<Object?>;
    return CaptureMetadata(
      sessionId: result[0]! as String,
      generation: result[1]! as int,
      sampleRate: result[2]! as int,
      channelCount: result[3]! as int,
      startedAtNanos: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(generation, other.generation) && _deepEquals(sampleRate, other.sampleRate) && _deepEquals(channelCount, other.channelCount) && _deepEquals(startedAtNanos, other.startedAtNanos);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureMetadata(sessionId: $sessionId, generation: $generation, sampleRate: $sampleRate, channelCount: $channelCount, startedAtNanos: $startedAtNanos)';
  }
}

class CaptureError {
  CaptureError({
    required this.code,
    required this.message,
  });

  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureError decode(Object result) {
    result as List<Object?>;
    return CaptureError(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureError(code: $code, message: $message)';
  }
}

class CapturePermissionResult {
  CapturePermissionResult({
    required this.result,
    this.error,
  });

  String result;

  CaptureError? error;

  List<Object?> _toList() {
    return <Object?>[
      result,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static CapturePermissionResult decode(Object result) {
    result as List<Object?>;
    return CapturePermissionResult(
      result: result[0]! as String,
      error: result[1] as CaptureError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CapturePermissionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(result, other.result) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CapturePermissionResult(result: $result, error: $error)';
  }
}

class CaptureResult {
  CaptureResult({
    required this.success,
    this.metadata,
    this.error,
  });

  bool success;

  CaptureMetadata? metadata;

  CaptureError? error;

  List<Object?> _toList() {
    return <Object?>[
      success,
      metadata,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureResult decode(Object result) {
    result as List<Object?>;
    return CaptureResult(
      success: result[0]! as bool,
      metadata: result[1] as CaptureMetadata?,
      error: result[2] as CaptureError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(metadata, other.metadata) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureResult(success: $success, metadata: $metadata, error: $error)';
  }
}

class CaptureStateResult {
  CaptureStateResult({
    required this.state,
    this.metadata,
  });

  CaptureState state;

  CaptureMetadata? metadata;

  List<Object?> _toList() {
    return <Object?>[
      state,
      metadata,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureStateResult decode(Object result) {
    result as List<Object?>;
    return CaptureStateResult(
      state: result[0]! as CaptureState,
      metadata: result[1] as CaptureMetadata?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureStateResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(metadata, other.metadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureStateResult(state: $state, metadata: $metadata)';
  }
}

class FrameArrivalStats {
  FrameArrivalStats({
    required this.totalFrames,
    required this.totalBytes,
    required this.silentFrames,
    required this.framesPerSecond,
    required this.bytesPerSecond,
    required this.timestampNanos,
    required this.isReceivingAudio,
    required this.peakAmplitude,
    required this.isSilent,
  });

  int totalFrames;

  int totalBytes;

  int silentFrames;

  int framesPerSecond;

  int bytesPerSecond;

  int timestampNanos;

  bool isReceivingAudio;

  int peakAmplitude;

  bool isSilent;

  List<Object?> _toList() {
    return <Object?>[
      totalFrames,
      totalBytes,
      silentFrames,
      framesPerSecond,
      bytesPerSecond,
      timestampNanos,
      isReceivingAudio,
      peakAmplitude,
      isSilent,
    ];
  }

  Object encode() {
    return _toList();  }

  static FrameArrivalStats decode(Object result) {
    result as List<Object?>;
    return FrameArrivalStats(
      totalFrames: result[0]! as int,
      totalBytes: result[1]! as int,
      silentFrames: result[2]! as int,
      framesPerSecond: result[3]! as int,
      bytesPerSecond: result[4]! as int,
      timestampNanos: result[5]! as int,
      isReceivingAudio: result[6]! as bool,
      peakAmplitude: result[7]! as int,
      isSilent: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FrameArrivalStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(totalFrames, other.totalFrames) && _deepEquals(totalBytes, other.totalBytes) && _deepEquals(silentFrames, other.silentFrames) && _deepEquals(framesPerSecond, other.framesPerSecond) && _deepEquals(bytesPerSecond, other.bytesPerSecond) && _deepEquals(timestampNanos, other.timestampNanos) && _deepEquals(isReceivingAudio, other.isReceivingAudio) && _deepEquals(peakAmplitude, other.peakAmplitude) && _deepEquals(isSilent, other.isSilent);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FrameArrivalStats(totalFrames: $totalFrames, totalBytes: $totalBytes, silentFrames: $silentFrames, framesPerSecond: $framesPerSecond, bytesPerSecond: $bytesPerSecond, timestampNanos: $timestampNanos, isReceivingAudio: $isReceivingAudio, peakAmplitude: $peakAmplitude, isSilent: $isSilent)';
  }
}

class StreamingMetadata {
  StreamingMetadata({
    required this.sessionId,
    required this.generation,
    required this.sampleRate,
    required this.channelCount,
    required this.startedAtNanos,
  });

  String sessionId;

  int generation;

  int sampleRate;

  int channelCount;

  int startedAtNanos;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      generation,
      sampleRate,
      channelCount,
      startedAtNanos,
    ];
  }

  Object encode() {
    return _toList();  }

  static StreamingMetadata decode(Object result) {
    result as List<Object?>;
    return StreamingMetadata(
      sessionId: result[0]! as String,
      generation: result[1]! as int,
      sampleRate: result[2]! as int,
      channelCount: result[3]! as int,
      startedAtNanos: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StreamingMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(generation, other.generation) && _deepEquals(sampleRate, other.sampleRate) && _deepEquals(channelCount, other.channelCount) && _deepEquals(startedAtNanos, other.startedAtNanos);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StreamingMetadata(sessionId: $sessionId, generation: $generation, sampleRate: $sampleRate, channelCount: $channelCount, startedAtNanos: $startedAtNanos)';
  }
}

class StreamingState {
  StreamingState({
    required this.state,
    this.metadata,
  });

  String state;

  StreamingMetadata? metadata;

  List<Object?> _toList() {
    return <Object?>[
      state,
      metadata,
    ];
  }

  Object encode() {
    return _toList();  }

  static StreamingState decode(Object result) {
    result as List<Object?>;
    return StreamingState(
      state: result[0]! as String,
      metadata: result[1] as StreamingMetadata?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StreamingState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(metadata, other.metadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StreamingState(state: $state, metadata: $metadata)';
  }
}

class ReceiveStats {
  ReceiveStats({
    required this.packetsReceived,
    required this.packetsLost,
    required this.packetsOutOfOrder,
    required this.bufferDepthMs,
    required this.lossRate,
    required this.timestampNanos,
    required this.isHealthy,
    required this.peakAmplitude,
    required this.isSilent,
  });

  int packetsReceived;

  int packetsLost;

  int packetsOutOfOrder;

  int bufferDepthMs;

  double lossRate;

  int timestampNanos;

  bool isHealthy;

  int peakAmplitude;

  bool isSilent;

  List<Object?> _toList() {
    return <Object?>[
      packetsReceived,
      packetsLost,
      packetsOutOfOrder,
      bufferDepthMs,
      lossRate,
      timestampNanos,
      isHealthy,
      peakAmplitude,
      isSilent,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReceiveStats decode(Object result) {
    result as List<Object?>;
    return ReceiveStats(
      packetsReceived: result[0]! as int,
      packetsLost: result[1]! as int,
      packetsOutOfOrder: result[2]! as int,
      bufferDepthMs: result[3]! as int,
      lossRate: result[4]! as double,
      timestampNanos: result[5]! as int,
      isHealthy: result[6]! as bool,
      peakAmplitude: result[7]! as int,
      isSilent: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReceiveStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packetsReceived, other.packetsReceived) && _deepEquals(packetsLost, other.packetsLost) && _deepEquals(packetsOutOfOrder, other.packetsOutOfOrder) && _deepEquals(bufferDepthMs, other.bufferDepthMs) && _deepEquals(lossRate, other.lossRate) && _deepEquals(timestampNanos, other.timestampNanos) && _deepEquals(isHealthy, other.isHealthy) && _deepEquals(peakAmplitude, other.peakAmplitude) && _deepEquals(isSilent, other.isSilent);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ReceiveStats(packetsReceived: $packetsReceived, packetsLost: $packetsLost, packetsOutOfOrder: $packetsOutOfOrder, bufferDepthMs: $bufferDepthMs, lossRate: $lossRate, timestampNanos: $timestampNanos, isHealthy: $isHealthy, peakAmplitude: $peakAmplitude, isSilent: $isSilent)';
  }
}

class ReceiveState {
  ReceiveState({
    required this.state,
    this.stats,
  });

  String state;

  ReceiveStats? stats;

  List<Object?> _toList() {
    return <Object?>[
      state,
      stats,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReceiveState decode(Object result) {
    result as List<Object?>;
    return ReceiveState(
      state: result[0]! as String,
      stats: result[1] as ReceiveStats?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReceiveState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(stats, other.stats);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ReceiveState(state: $state, stats: $stats)';
  }
}

class OutputState {
  OutputState({
    required this.state,
    required this.bufferedMs,
  });

  String state;

  int bufferedMs;

  List<Object?> _toList() {
    return <Object?>[
      state,
      bufferedMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static OutputState decode(Object result) {
    result as List<Object?>;
    return OutputState(
      state: result[0]! as String,
      bufferedMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OutputState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(bufferedMs, other.bufferedMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OutputState(state: $state, bufferedMs: $bufferedMs)';
  }
}

class OutputError {
  OutputError({
    required this.code,
    required this.message,
  });

  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static OutputError decode(Object result) {
    result as List<Object?>;
    return OutputError(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OutputError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OutputError(code: $code, message: $message)';
  }
}

class ScheduleResult {
  ScheduleResult({
    required this.success,
    this.errorCode,
    this.errorMessage,
  });

  bool success;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      success,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScheduleResult decode(Object result) {
    result as List<Object?>;
    return ScheduleResult(
      success: result[0]! as bool,
      errorCode: result[1] as String?,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScheduleResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScheduleResult(success: $success, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}

class NextFrameInfo {
  NextFrameInfo({
    required this.framePosition,
    required this.sequenceNumber,
    required this.generation,
    required this.sampleRate,
    required this.channelCount,
  });

  int framePosition;

  int sequenceNumber;

  int generation;

  int sampleRate;

  int channelCount;

  List<Object?> _toList() {
    return <Object?>[
      framePosition,
      sequenceNumber,
      generation,
      sampleRate,
      channelCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static NextFrameInfo decode(Object result) {
    result as List<Object?>;
    return NextFrameInfo(
      framePosition: result[0]! as int,
      sequenceNumber: result[1]! as int,
      generation: result[2]! as int,
      sampleRate: result[3]! as int,
      channelCount: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NextFrameInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(framePosition, other.framePosition) && _deepEquals(sequenceNumber, other.sequenceNumber) && _deepEquals(generation, other.generation) && _deepEquals(sampleRate, other.sampleRate) && _deepEquals(channelCount, other.channelCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NextFrameInfo(framePosition: $framePosition, sequenceNumber: $sequenceNumber, generation: $generation, sampleRate: $sampleRate, channelCount: $channelCount)';
  }
}

class PipelineError {
  PipelineError({
    required this.code,
    required this.message,
    required this.generation,
  });

  String code;

  String message;

  int generation;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
      generation,
    ];
  }

  Object encode() {
    return _toList();  }

  static PipelineError decode(Object result) {
    result as List<Object?>;
    return PipelineError(
      code: result[0]! as String,
      message: result[1]! as String,
      generation: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PipelineError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message) && _deepEquals(generation, other.generation);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PipelineError(code: $code, message: $message, generation: $generation)';
  }
}

class TimeSyncResponse {
  TimeSyncResponse({
    required this.t1,
    required this.t2,
    required this.t3,
    required this.generation,
    required this.sessionId,
  });

  int t1;

  int t2;

  int t3;

  int generation;

  String sessionId;

  List<Object?> _toList() {
    return <Object?>[
      t1,
      t2,
      t3,
      generation,
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static TimeSyncResponse decode(Object result) {
    result as List<Object?>;
    return TimeSyncResponse(
      t1: result[0]! as int,
      t2: result[1]! as int,
      t3: result[2]! as int,
      generation: result[3]! as int,
      sessionId: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TimeSyncResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(t1, other.t1) && _deepEquals(t2, other.t2) && _deepEquals(t3, other.t3) && _deepEquals(generation, other.generation) && _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TimeSyncResponse(t1: $t1, t2: $t2, t3: $t3, generation: $generation, sessionId: $sessionId)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ConnectionState) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureState) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureMetadata) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureError) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is CapturePermissionResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureStateResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is FrameArrivalStats) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is StreamingMetadata) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is StreamingState) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is ReceiveStats) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is ReceiveState) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is OutputState) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is OutputError) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is ScheduleResult) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is NextFrameInfo) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is PipelineError) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is TimeSyncResponse) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ConnectionState.decode(readValue(buffer)!);
      case 130:
        return DeviceInfo.decode(readValue(buffer)!);
      case 131:
        return CaptureState.decode(readValue(buffer)!);
      case 132:
        return CaptureMetadata.decode(readValue(buffer)!);
      case 133:
        return CaptureError.decode(readValue(buffer)!);
      case 134:
        return CapturePermissionResult.decode(readValue(buffer)!);
      case 135:
        return CaptureResult.decode(readValue(buffer)!);
      case 136:
        return CaptureStateResult.decode(readValue(buffer)!);
      case 137:
        return FrameArrivalStats.decode(readValue(buffer)!);
      case 138:
        return StreamingMetadata.decode(readValue(buffer)!);
      case 139:
        return StreamingState.decode(readValue(buffer)!);
      case 140:
        return ReceiveStats.decode(readValue(buffer)!);
      case 141:
        return ReceiveState.decode(readValue(buffer)!);
      case 142:
        return OutputState.decode(readValue(buffer)!);
      case 143:
        return OutputError.decode(readValue(buffer)!);
      case 144:
        return ScheduleResult.decode(readValue(buffer)!);
      case 145:
        return NextFrameInfo.decode(readValue(buffer)!);
      case 146:
        return PipelineError.decode(readValue(buffer)!);
      case 147:
        return TimeSyncResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AudioOutputPlatform {
  /// Constructor for [AudioOutputPlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AudioOutputPlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<OutputState> getOutputState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioOutputPlatform.getOutputState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OutputState;
  }

  Future<ScheduleResult> scheduleFrame(int framePosition, int targetNativeTimeNanos, int generation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioOutputPlatform.scheduleFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[framePosition, targetNativeTimeNanos, generation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ScheduleResult;
  }
}

abstract class AudioOutputFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onOutputStateChanged(String state, int bufferedMs);

  void onOutputError(String errorCode, String errorMessage);

  void requestScheduleTarget(int framePosition, int captureTimestampNs, int generation);

  static void setUp(AudioOutputFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.onOutputStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          final int arg_bufferedMs = args[1]! as int;
          try {
            api.onOutputStateChanged(arg_state, arg_bufferedMs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.onOutputError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_errorCode = args[0]! as String;
          final String arg_errorMessage = args[1]! as String;
          try {
            api.onOutputError(arg_errorCode, arg_errorMessage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.requestScheduleTarget$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_framePosition = args[0]! as int;
          final int arg_captureTimestampNs = args[1]! as int;
          final int arg_generation = args[2]! as int;
          try {
            api.requestScheduleTarget(arg_framePosition, arg_captureTimestampNs, arg_generation);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class NetworkHostPlatform {
  /// Constructor for [NetworkHostPlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NetworkHostPlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> startHosting(int port) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.startHosting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[port]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> connectToHost(String ipAddress, int port) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.connectToHost$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ipAddress, port]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> sendMessage(String message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> sendChatMessage(String text) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendChatMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> sendProtocolMessage(String message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendProtocolMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> disconnect() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String> getLocalIpAddress() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.getLocalIpAddress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> setHeartbeatConfig(int intervalMs, int timeoutMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.setHeartbeatConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[intervalMs, timeoutMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> reconnectToHost(String ipAddress, int port) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.NetworkHostPlatform.reconnectToHost$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ipAddress, port]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

class DevicePlatform {
  /// Constructor for [DevicePlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DevicePlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<DeviceInfo> getDeviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.DevicePlatform.getDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DeviceInfo;
  }
}

class TimingPlatform {
  /// Constructor for [TimingPlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TimingPlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> getMonotonicTimeNanos() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.TimingPlatform.getMonotonicTimeNanos$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }
}

class AudioCapturePlatform {
  /// Constructor for [AudioCapturePlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AudioCapturePlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CapturePermissionResult> requestCapturePermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.requestCapturePermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CapturePermissionResult;
  }

  Future<CaptureResult> startCapture() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.startCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CaptureResult;
  }

  Future<void> stopCapture() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.stopCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<CaptureStateResult> getCaptureState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.getCaptureState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CaptureStateResult;
  }

  Future<bool> isIgnoringBatteryOptimizations() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.isIgnoringBatteryOptimizations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> requestIgnoreBatteryOptimizations() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.requestIgnoreBatteryOptimizations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startStreaming() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.startStreaming$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopStreaming() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.stopStreaming$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<StreamingState> getStreamingState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioCapturePlatform.getStreamingState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StreamingState;
  }
}

class AudioReceivePlatform {
  /// Constructor for [AudioReceivePlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AudioReceivePlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<ReceiveState> getReceiveState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioReceivePlatform.getReceiveState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ReceiveState;
  }

  Future<NextFrameInfo?> getNextFrameInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.AudioReceivePlatform.getNextFrameInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as NextFrameInfo?;
  }
}

abstract class NetworkFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onMessageReceived(String message);

  void onConnectionStateChanged(String state);

  void onConnectionError(String errorCode, String errorMessage);

  static void setUp(NetworkFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onMessageReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_message = args[0]! as String;
          try {
            api.onMessageReceived(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          try {
            api.onConnectionStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_errorCode = args[0]! as String;
          final String arg_errorMessage = args[1]! as String;
          try {
            api.onConnectionError(arg_errorCode, arg_errorMessage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class AudioCaptureFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCaptureStateChanged(String state, CaptureMetadata? metadata);

  void onCaptureError(String errorCode, String errorMessage);

  void onCaptureFramesReceived(FrameArrivalStats stats);

  void onStreamStateChanged(String state, StreamingMetadata? metadata);

  void onStreamError(String errorCode, String errorMessage);

  static void setUp(AudioCaptureFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          final CaptureMetadata? arg_metadata = args[1] as CaptureMetadata?;
          try {
            api.onCaptureStateChanged(arg_state, arg_metadata);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_errorCode = args[0]! as String;
          final String arg_errorMessage = args[1]! as String;
          try {
            api.onCaptureError(arg_errorCode, arg_errorMessage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureFramesReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final FrameArrivalStats arg_stats = args[0]! as FrameArrivalStats;
          try {
            api.onCaptureFramesReceived(arg_stats);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onStreamStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          final StreamingMetadata? arg_metadata = args[1] as StreamingMetadata?;
          try {
            api.onStreamStateChanged(arg_state, arg_metadata);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onStreamError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_errorCode = args[0]! as String;
          final String arg_errorMessage = args[1]! as String;
          try {
            api.onStreamError(arg_errorCode, arg_errorMessage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class AudioReceiveFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStreamStateChanged(String state, ReceiveStats? stats);

  void onAudioLevelUpdate(int peakAmplitude, bool isSilent);

  static void setUp(AudioReceiveFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioReceiveFlutterApi.onStreamStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          final ReceiveStats? arg_stats = args[1] as ReceiveStats?;
          try {
            api.onStreamStateChanged(arg_state, arg_stats);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.AudioReceiveFlutterApi.onAudioLevelUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_peakAmplitude = args[0]! as int;
          final bool arg_isSilent = args[1]! as bool;
          try {
            api.onAudioLevelUpdate(arg_peakAmplitude, arg_isSilent);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class PipelineFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPipelineStateChanged(String state, int generation);

  void onPipelineError(PipelineError error);

  void onTimeSyncResponse(TimeSyncResponse response);

  void onSyncStateChanged(String state, int generation);

  static void setUp(PipelineFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onPipelineStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          final int arg_generation = args[1]! as int;
          try {
            api.onPipelineStateChanged(arg_state, arg_generation);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onPipelineError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PipelineError arg_error = args[0]! as PipelineError;
          try {
            api.onPipelineError(arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onTimeSyncResponse$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final TimeSyncResponse arg_response = args[0]! as TimeSyncResponse;
          try {
            api.onTimeSyncResponse(arg_response);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onSyncStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_state = args[0]! as String;
          final int arg_generation = args[1]! as int;
          try {
            api.onSyncStateChanged(arg_state, arg_generation);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class PipelinePlatform {
  /// Constructor for [PipelinePlatform]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PipelinePlatform({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startPipeline() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.PipelinePlatform.startPipeline$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopPipeline() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.PipelinePlatform.stopPipeline$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> getPipelineGeneration() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.PipelinePlatform.getPipelineGeneration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<String> getPipelineState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.PipelinePlatform.getPipelineState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> getSyncState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.PipelinePlatform.getSyncState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> updateSyncState(String state, int generation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.soundmesh.PipelinePlatform.updateSyncState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[state, generation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
