// Copyright 2026 SoundMesh. All rights reserved.
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum SoundMeshMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionState: Hashable, CustomStringConvertible {
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionState? {
    let state = pigeonVar_list[0] as! String

    return ConnectionState(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: ConnectionState, rhs: ConnectionState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionState")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "ConnectionState(state: \(String(describing: state)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceInfo: Hashable, CustomStringConvertible {
  var platformName: String
  var osVersion: String
  var deviceModel: String
  var brand: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceInfo? {
    let platformName = pigeonVar_list[0] as! String
    let osVersion = pigeonVar_list[1] as! String
    let deviceModel = pigeonVar_list[2] as! String
    let brand: String? = nilOrValue(pigeonVar_list[3])

    return DeviceInfo(
      platformName: platformName,
      osVersion: osVersion,
      deviceModel: deviceModel,
      brand: brand
    )
  }
  func toList() -> [Any?] {
    return [
      platformName,
      osVersion,
      deviceModel,
      brand,
    ]
  }
  static func == (lhs: DeviceInfo, rhs: DeviceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.platformName, rhs.platformName) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.deviceModel, rhs.deviceModel) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.brand, rhs.brand)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceInfo")
    SoundMeshMessagesPigeonInternal.deepHash(value: platformName, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: deviceModel, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: brand, hasher: &hasher)
  }

  public var description: String {
    return "DeviceInfo(platformName: \(String(describing: platformName)), osVersion: \(String(describing: osVersion)), deviceModel: \(String(describing: deviceModel)), brand: \(String(describing: brand)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureState: Hashable, CustomStringConvertible {
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureState? {
    let state = pigeonVar_list[0] as! String

    return CaptureState(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: CaptureState, rhs: CaptureState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureState")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "CaptureState(state: \(String(describing: state)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureMetadata: Hashable, CustomStringConvertible {
  var sessionId: String
  var generation: Int64
  var sampleRate: Int64
  var channelCount: Int64
  var startedAtNanos: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureMetadata? {
    let sessionId = pigeonVar_list[0] as! String
    let generation = pigeonVar_list[1] as! Int64
    let sampleRate = pigeonVar_list[2] as! Int64
    let channelCount = pigeonVar_list[3] as! Int64
    let startedAtNanos = pigeonVar_list[4] as! Int64

    return CaptureMetadata(
      sessionId: sessionId,
      generation: generation,
      sampleRate: sampleRate,
      channelCount: channelCount,
      startedAtNanos: startedAtNanos
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      generation,
      sampleRate,
      channelCount,
      startedAtNanos,
    ]
  }
  static func == (lhs: CaptureMetadata, rhs: CaptureMetadata) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.generation, rhs.generation) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.channelCount, rhs.channelCount) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.startedAtNanos, rhs.startedAtNanos)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureMetadata")
    SoundMeshMessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: generation, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: channelCount, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: startedAtNanos, hasher: &hasher)
  }

  public var description: String {
    return "CaptureMetadata(sessionId: \(String(describing: sessionId)), generation: \(String(describing: generation)), sampleRate: \(String(describing: sampleRate)), channelCount: \(String(describing: channelCount)), startedAtNanos: \(String(describing: startedAtNanos)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureError: Hashable, CustomStringConvertible {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return CaptureError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: CaptureError, rhs: CaptureError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureError")
    SoundMeshMessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "CaptureError(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CapturePermissionResult: Hashable, CustomStringConvertible {
  var result: String
  var error: CaptureError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CapturePermissionResult? {
    let result = pigeonVar_list[0] as! String
    let error: CaptureError? = nilOrValue(pigeonVar_list[1])

    return CapturePermissionResult(
      result: result,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      result,
      error,
    ]
  }
  static func == (lhs: CapturePermissionResult, rhs: CapturePermissionResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.result, rhs.result) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CapturePermissionResult")
    SoundMeshMessagesPigeonInternal.deepHash(value: result, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "CapturePermissionResult(result: \(String(describing: result)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureResult: Hashable, CustomStringConvertible {
  var success: Bool
  var metadata: CaptureMetadata? = nil
  var error: CaptureError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureResult? {
    let success = pigeonVar_list[0] as! Bool
    let metadata: CaptureMetadata? = nilOrValue(pigeonVar_list[1])
    let error: CaptureError? = nilOrValue(pigeonVar_list[2])

    return CaptureResult(
      success: success,
      metadata: metadata,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      metadata,
      error,
    ]
  }
  static func == (lhs: CaptureResult, rhs: CaptureResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.success, rhs.success) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.metadata, rhs.metadata) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureResult")
    SoundMeshMessagesPigeonInternal.deepHash(value: success, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: metadata, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "CaptureResult(success: \(String(describing: success)), metadata: \(String(describing: metadata)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureStateResult: Hashable, CustomStringConvertible {
  var state: CaptureState
  var metadata: CaptureMetadata? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureStateResult? {
    let state = pigeonVar_list[0] as! CaptureState
    let metadata: CaptureMetadata? = nilOrValue(pigeonVar_list[1])

    return CaptureStateResult(
      state: state,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      metadata,
    ]
  }
  static func == (lhs: CaptureStateResult, rhs: CaptureStateResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureStateResult")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: metadata, hasher: &hasher)
  }

  public var description: String {
    return "CaptureStateResult(state: \(String(describing: state)), metadata: \(String(describing: metadata)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FrameArrivalStats: Hashable, CustomStringConvertible {
  var totalFrames: Int64
  var totalBytes: Int64
  var silentFrames: Int64
  var framesPerSecond: Int64
  var bytesPerSecond: Int64
  var timestampNanos: Int64
  var isReceivingAudio: Bool
  var peakAmplitude: Int64
  var isSilent: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FrameArrivalStats? {
    let totalFrames = pigeonVar_list[0] as! Int64
    let totalBytes = pigeonVar_list[1] as! Int64
    let silentFrames = pigeonVar_list[2] as! Int64
    let framesPerSecond = pigeonVar_list[3] as! Int64
    let bytesPerSecond = pigeonVar_list[4] as! Int64
    let timestampNanos = pigeonVar_list[5] as! Int64
    let isReceivingAudio = pigeonVar_list[6] as! Bool
    let peakAmplitude = pigeonVar_list[7] as! Int64
    let isSilent = pigeonVar_list[8] as! Bool

    return FrameArrivalStats(
      totalFrames: totalFrames,
      totalBytes: totalBytes,
      silentFrames: silentFrames,
      framesPerSecond: framesPerSecond,
      bytesPerSecond: bytesPerSecond,
      timestampNanos: timestampNanos,
      isReceivingAudio: isReceivingAudio,
      peakAmplitude: peakAmplitude,
      isSilent: isSilent
    )
  }
  func toList() -> [Any?] {
    return [
      totalFrames,
      totalBytes,
      silentFrames,
      framesPerSecond,
      bytesPerSecond,
      timestampNanos,
      isReceivingAudio,
      peakAmplitude,
      isSilent,
    ]
  }
  static func == (lhs: FrameArrivalStats, rhs: FrameArrivalStats) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.totalFrames, rhs.totalFrames) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.totalBytes, rhs.totalBytes) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.silentFrames, rhs.silentFrames) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.framesPerSecond, rhs.framesPerSecond) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.bytesPerSecond, rhs.bytesPerSecond) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.timestampNanos, rhs.timestampNanos) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.isReceivingAudio, rhs.isReceivingAudio) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.peakAmplitude, rhs.peakAmplitude) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.isSilent, rhs.isSilent)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FrameArrivalStats")
    SoundMeshMessagesPigeonInternal.deepHash(value: totalFrames, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: totalBytes, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: silentFrames, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: framesPerSecond, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: bytesPerSecond, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: timestampNanos, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: isReceivingAudio, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: peakAmplitude, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: isSilent, hasher: &hasher)
  }

  public var description: String {
    return "FrameArrivalStats(totalFrames: \(String(describing: totalFrames)), totalBytes: \(String(describing: totalBytes)), silentFrames: \(String(describing: silentFrames)), framesPerSecond: \(String(describing: framesPerSecond)), bytesPerSecond: \(String(describing: bytesPerSecond)), timestampNanos: \(String(describing: timestampNanos)), isReceivingAudio: \(String(describing: isReceivingAudio)), peakAmplitude: \(String(describing: peakAmplitude)), isSilent: \(String(describing: isSilent)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StreamingMetadata: Hashable, CustomStringConvertible {
  var sessionId: String
  var generation: Int64
  var sampleRate: Int64
  var channelCount: Int64
  var startedAtNanos: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StreamingMetadata? {
    let sessionId = pigeonVar_list[0] as! String
    let generation = pigeonVar_list[1] as! Int64
    let sampleRate = pigeonVar_list[2] as! Int64
    let channelCount = pigeonVar_list[3] as! Int64
    let startedAtNanos = pigeonVar_list[4] as! Int64

    return StreamingMetadata(
      sessionId: sessionId,
      generation: generation,
      sampleRate: sampleRate,
      channelCount: channelCount,
      startedAtNanos: startedAtNanos
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      generation,
      sampleRate,
      channelCount,
      startedAtNanos,
    ]
  }
  static func == (lhs: StreamingMetadata, rhs: StreamingMetadata) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.generation, rhs.generation) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.channelCount, rhs.channelCount) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.startedAtNanos, rhs.startedAtNanos)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StreamingMetadata")
    SoundMeshMessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: generation, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: channelCount, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: startedAtNanos, hasher: &hasher)
  }

  public var description: String {
    return "StreamingMetadata(sessionId: \(String(describing: sessionId)), generation: \(String(describing: generation)), sampleRate: \(String(describing: sampleRate)), channelCount: \(String(describing: channelCount)), startedAtNanos: \(String(describing: startedAtNanos)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StreamingState: Hashable, CustomStringConvertible {
  var state: String
  var metadata: StreamingMetadata? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StreamingState? {
    let state = pigeonVar_list[0] as! String
    let metadata: StreamingMetadata? = nilOrValue(pigeonVar_list[1])

    return StreamingState(
      state: state,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      metadata,
    ]
  }
  static func == (lhs: StreamingState, rhs: StreamingState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.metadata, rhs.metadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StreamingState")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: metadata, hasher: &hasher)
  }

  public var description: String {
    return "StreamingState(state: \(String(describing: state)), metadata: \(String(describing: metadata)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReceiveStats: Hashable, CustomStringConvertible {
  var packetsReceived: Int64
  var packetsLost: Int64
  var packetsOutOfOrder: Int64
  var bufferDepthMs: Int64
  var lossRate: Double
  var timestampNanos: Int64
  var isHealthy: Bool
  var peakAmplitude: Int64
  var isSilent: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReceiveStats? {
    let packetsReceived = pigeonVar_list[0] as! Int64
    let packetsLost = pigeonVar_list[1] as! Int64
    let packetsOutOfOrder = pigeonVar_list[2] as! Int64
    let bufferDepthMs = pigeonVar_list[3] as! Int64
    let lossRate = pigeonVar_list[4] as! Double
    let timestampNanos = pigeonVar_list[5] as! Int64
    let isHealthy = pigeonVar_list[6] as! Bool
    let peakAmplitude = pigeonVar_list[7] as! Int64
    let isSilent = pigeonVar_list[8] as! Bool

    return ReceiveStats(
      packetsReceived: packetsReceived,
      packetsLost: packetsLost,
      packetsOutOfOrder: packetsOutOfOrder,
      bufferDepthMs: bufferDepthMs,
      lossRate: lossRate,
      timestampNanos: timestampNanos,
      isHealthy: isHealthy,
      peakAmplitude: peakAmplitude,
      isSilent: isSilent
    )
  }
  func toList() -> [Any?] {
    return [
      packetsReceived,
      packetsLost,
      packetsOutOfOrder,
      bufferDepthMs,
      lossRate,
      timestampNanos,
      isHealthy,
      peakAmplitude,
      isSilent,
    ]
  }
  static func == (lhs: ReceiveStats, rhs: ReceiveStats) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.packetsReceived, rhs.packetsReceived) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.packetsLost, rhs.packetsLost) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.packetsOutOfOrder, rhs.packetsOutOfOrder) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.bufferDepthMs, rhs.bufferDepthMs) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.lossRate, rhs.lossRate) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.timestampNanos, rhs.timestampNanos) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.isHealthy, rhs.isHealthy) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.peakAmplitude, rhs.peakAmplitude) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.isSilent, rhs.isSilent)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReceiveStats")
    SoundMeshMessagesPigeonInternal.deepHash(value: packetsReceived, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: packetsLost, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: packetsOutOfOrder, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: bufferDepthMs, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: lossRate, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: timestampNanos, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: isHealthy, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: peakAmplitude, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: isSilent, hasher: &hasher)
  }

  public var description: String {
    return "ReceiveStats(packetsReceived: \(String(describing: packetsReceived)), packetsLost: \(String(describing: packetsLost)), packetsOutOfOrder: \(String(describing: packetsOutOfOrder)), bufferDepthMs: \(String(describing: bufferDepthMs)), lossRate: \(String(describing: lossRate)), timestampNanos: \(String(describing: timestampNanos)), isHealthy: \(String(describing: isHealthy)), peakAmplitude: \(String(describing: peakAmplitude)), isSilent: \(String(describing: isSilent)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReceiveState: Hashable, CustomStringConvertible {
  var state: String
  var stats: ReceiveStats? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReceiveState? {
    let state = pigeonVar_list[0] as! String
    let stats: ReceiveStats? = nilOrValue(pigeonVar_list[1])

    return ReceiveState(
      state: state,
      stats: stats
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      stats,
    ]
  }
  static func == (lhs: ReceiveState, rhs: ReceiveState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.stats, rhs.stats)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReceiveState")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: stats, hasher: &hasher)
  }

  public var description: String {
    return "ReceiveState(state: \(String(describing: state)), stats: \(String(describing: stats)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OutputState: Hashable, CustomStringConvertible {
  var state: String
  var bufferedMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OutputState? {
    let state = pigeonVar_list[0] as! String
    let bufferedMs = pigeonVar_list[1] as! Int64

    return OutputState(
      state: state,
      bufferedMs: bufferedMs
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      bufferedMs,
    ]
  }
  static func == (lhs: OutputState, rhs: OutputState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.bufferedMs, rhs.bufferedMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OutputState")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: bufferedMs, hasher: &hasher)
  }

  public var description: String {
    return "OutputState(state: \(String(describing: state)), bufferedMs: \(String(describing: bufferedMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OutputError: Hashable, CustomStringConvertible {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OutputError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return OutputError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: OutputError, rhs: OutputError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OutputError")
    SoundMeshMessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "OutputError(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipelineError: Hashable, CustomStringConvertible {
  var code: String
  var message: String
  var generation: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipelineError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let generation = pigeonVar_list[2] as! Int64

    return PipelineError(
      code: code,
      message: message,
      generation: generation
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      generation,
    ]
  }
  static func == (lhs: PipelineError, rhs: PipelineError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.generation, rhs.generation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PipelineError")
    SoundMeshMessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: generation, hasher: &hasher)
  }

  public var description: String {
    return "PipelineError(code: \(String(describing: code)), message: \(String(describing: message)), generation: \(String(describing: generation)))"
  }
}

private class SoundMeshMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ConnectionState.fromList(self.readValue() as! [Any?])
    case 130:
      return DeviceInfo.fromList(self.readValue() as! [Any?])
    case 131:
      return CaptureState.fromList(self.readValue() as! [Any?])
    case 132:
      return CaptureMetadata.fromList(self.readValue() as! [Any?])
    case 133:
      return CaptureError.fromList(self.readValue() as! [Any?])
    case 134:
      return CapturePermissionResult.fromList(self.readValue() as! [Any?])
    case 135:
      return CaptureResult.fromList(self.readValue() as! [Any?])
    case 136:
      return CaptureStateResult.fromList(self.readValue() as! [Any?])
    case 137:
      return FrameArrivalStats.fromList(self.readValue() as! [Any?])
    case 138:
      return StreamingMetadata.fromList(self.readValue() as! [Any?])
    case 139:
      return StreamingState.fromList(self.readValue() as! [Any?])
    case 140:
      return ReceiveStats.fromList(self.readValue() as! [Any?])
    case 141:
      return ReceiveState.fromList(self.readValue() as! [Any?])
    case 142:
      return OutputState.fromList(self.readValue() as! [Any?])
    case 143:
      return OutputError.fromList(self.readValue() as! [Any?])
    case 144:
      return PipelineError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SoundMeshMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionState {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureState {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureMetadata {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureError {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CapturePermissionResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureStateResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? FrameArrivalStats {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? StreamingMetadata {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? StreamingState {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ReceiveStats {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? ReceiveState {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? OutputState {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? OutputError {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PipelineError {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SoundMeshMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SoundMeshMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SoundMeshMessagesPigeonCodecWriter(data: data)
  }
}

class SoundMeshMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SoundMeshMessagesPigeonCodec(readerWriter: SoundMeshMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioOutputPlatform {
  func getOutputState() throws -> OutputState
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioOutputPlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioOutputPlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioOutputPlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getOutputStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioOutputPlatform.getOutputState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOutputStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getOutputState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getOutputStateChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AudioOutputFlutterApiProtocol {
  func onOutputStateChanged(state stateArg: String, bufferedMs bufferedMsArg: Int64) async throws
  func onOutputError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws
}
class AudioOutputFlutterApi: AudioOutputFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SoundMeshMessagesPigeonCodec {
    return SoundMeshMessagesPigeonCodec.shared
  }
  func onOutputStateChanged(state stateArg: String, bufferedMs bufferedMsArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.onOutputStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg, bufferedMsArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onOutputError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioOutputFlutterApi.onOutputError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([errorCodeArg, errorMessageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NetworkHostPlatform {
  func startHosting(port: Int64) throws -> Bool
  func connectToHost(ipAddress: String, port: Int64) throws -> Bool
  func sendMessage(message: String) throws -> Bool
  func sendChatMessage(text: String) throws -> Bool
  func sendProtocolMessage(message: String) throws -> Bool
  func disconnect() throws
  func getLocalIpAddress() throws -> String
  func setHeartbeatConfig(intervalMs: Int64, timeoutMs: Int64) async throws
  func reconnectToHost(ipAddress: String, port: Int64) async throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NetworkHostPlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `NetworkHostPlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NetworkHostPlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startHostingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.startHosting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startHostingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let portArg = args[0] as! Int64
        do {
          let result = try api.startHosting(port: portArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startHostingChannel.setMessageHandler(nil)
    }
    let connectToHostChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.connectToHost\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectToHostChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ipAddressArg = args[0] as! String
        let portArg = args[1] as! Int64
        do {
          let result = try api.connectToHost(ipAddress: ipAddressArg, port: portArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectToHostChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        do {
          let result = try api.sendMessage(message: messageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let sendChatMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendChatMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendChatMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          let result = try api.sendChatMessage(text: textArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendChatMessageChannel.setMessageHandler(nil)
    }
    let sendProtocolMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendProtocolMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendProtocolMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        do {
          let result = try api.sendProtocolMessage(message: messageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendProtocolMessageChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        do {
          try api.disconnect()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let getLocalIpAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.getLocalIpAddress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocalIpAddressChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLocalIpAddress()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLocalIpAddressChannel.setMessageHandler(nil)
    }
    let setHeartbeatConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.setHeartbeatConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHeartbeatConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let intervalMsArg = args[0] as! Int64
        let timeoutMsArg = args[1] as! Int64
        Task { @MainActor in
          do {
            try await api.setHeartbeatConfig(intervalMs: intervalMsArg, timeoutMs: timeoutMsArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setHeartbeatConfigChannel.setMessageHandler(nil)
    }
    let reconnectToHostChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.reconnectToHost\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reconnectToHostChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ipAddressArg = args[0] as! String
        let portArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.reconnectToHost(ipAddress: ipAddressArg, port: portArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      reconnectToHostChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DevicePlatform {
  func getDeviceInfo() throws -> DeviceInfo
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DevicePlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `DevicePlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DevicePlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.DevicePlatform.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TimingPlatform {
  func getMonotonicTimeNanos() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TimingPlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `TimingPlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TimingPlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getMonotonicTimeNanosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.TimingPlatform.getMonotonicTimeNanos\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMonotonicTimeNanosChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMonotonicTimeNanos()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMonotonicTimeNanosChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioCapturePlatform {
  func requestCapturePermission() async throws -> CapturePermissionResult
  func startCapture() async throws -> CaptureResult
  func stopCapture() async throws
  func getCaptureState() throws -> CaptureStateResult
  func isIgnoringBatteryOptimizations() throws -> Bool
  func requestIgnoreBatteryOptimizations() async throws
  func startStreaming() async throws
  func stopStreaming() async throws
  func getStreamingState() throws -> StreamingState
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioCapturePlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioCapturePlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioCapturePlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestCapturePermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.requestCapturePermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCapturePermissionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestCapturePermission()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCapturePermissionChannel.setMessageHandler(nil)
    }
    let startCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.startCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCaptureChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.startCapture()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startCaptureChannel.setMessageHandler(nil)
    }
    let stopCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.stopCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopCaptureChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.stopCapture()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopCaptureChannel.setMessageHandler(nil)
    }
    let getCaptureStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.getCaptureState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCaptureStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCaptureState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCaptureStateChannel.setMessageHandler(nil)
    }
    let isIgnoringBatteryOptimizationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.isIgnoringBatteryOptimizations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isIgnoringBatteryOptimizationsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isIgnoringBatteryOptimizations()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isIgnoringBatteryOptimizationsChannel.setMessageHandler(nil)
    }
    let requestIgnoreBatteryOptimizationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.requestIgnoreBatteryOptimizations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestIgnoreBatteryOptimizationsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.requestIgnoreBatteryOptimizations()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestIgnoreBatteryOptimizationsChannel.setMessageHandler(nil)
    }
    let startStreamingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.startStreaming\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startStreamingChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.startStreaming()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startStreamingChannel.setMessageHandler(nil)
    }
    let stopStreamingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.stopStreaming\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopStreamingChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.stopStreaming()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopStreamingChannel.setMessageHandler(nil)
    }
    let getStreamingStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioCapturePlatform.getStreamingState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStreamingStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getStreamingState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStreamingStateChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioReceivePlatform {
  func getReceiveState() throws -> ReceiveState
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioReceivePlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioReceivePlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioReceivePlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getReceiveStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.AudioReceivePlatform.getReceiveState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getReceiveStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getReceiveState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getReceiveStateChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NetworkFlutterApiProtocol {
  func onMessageReceived(message messageArg: String) async throws
  func onConnectionStateChanged(state stateArg: String) async throws
  func onConnectionError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws
}
class NetworkFlutterApi: NetworkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SoundMeshMessagesPigeonCodec {
    return SoundMeshMessagesPigeonCodec.shared
  }
  func onMessageReceived(message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onMessageReceived\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onConnectionStateChanged(state stateArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onConnectionError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([errorCodeArg, errorMessageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AudioCaptureFlutterApiProtocol {
  func onCaptureStateChanged(state stateArg: String, metadata metadataArg: CaptureMetadata?) async throws
  func onCaptureError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws
  func onCaptureFramesReceived(stats statsArg: FrameArrivalStats) async throws
  func onStreamStateChanged(state stateArg: String, metadata metadataArg: StreamingMetadata?) async throws
  func onStreamError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws
}
class AudioCaptureFlutterApi: AudioCaptureFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SoundMeshMessagesPigeonCodec {
    return SoundMeshMessagesPigeonCodec.shared
  }
  func onCaptureStateChanged(state stateArg: String, metadata metadataArg: CaptureMetadata?) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg, metadataArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onCaptureError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([errorCodeArg, errorMessageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onCaptureFramesReceived(stats statsArg: FrameArrivalStats) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onCaptureFramesReceived\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([statsArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onStreamStateChanged(state stateArg: String, metadata metadataArg: StreamingMetadata?) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onStreamStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg, metadataArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onStreamError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioCaptureFlutterApi.onStreamError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([errorCodeArg, errorMessageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AudioReceiveFlutterApiProtocol {
  func onStreamStateChanged(state stateArg: String, stats statsArg: ReceiveStats?) async throws
  func onAudioLevelUpdate(peakAmplitude peakAmplitudeArg: Int64, isSilent isSilentArg: Bool) async throws
}
class AudioReceiveFlutterApi: AudioReceiveFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SoundMeshMessagesPigeonCodec {
    return SoundMeshMessagesPigeonCodec.shared
  }
  func onStreamStateChanged(state stateArg: String, stats statsArg: ReceiveStats?) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioReceiveFlutterApi.onStreamStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg, statsArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onAudioLevelUpdate(peakAmplitude peakAmplitudeArg: Int64, isSilent isSilentArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.AudioReceiveFlutterApi.onAudioLevelUpdate\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([peakAmplitudeArg, isSilentArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PipelineFlutterApiProtocol {
  func onPipelineStateChanged(state stateArg: String, generation generationArg: Int64) async throws
  func onPipelineError(error errorArg: PipelineError) async throws
}
class PipelineFlutterApi: PipelineFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SoundMeshMessagesPigeonCodec {
    return SoundMeshMessagesPigeonCodec.shared
  }
  func onPipelineStateChanged(state stateArg: String, generation generationArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onPipelineStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg, generationArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onPipelineError(error errorArg: PipelineError) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.PipelineFlutterApi.onPipelineError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([errorArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PipelinePlatform {
  func startPipeline() async throws
  func stopPipeline() async throws
  func getPipelineGeneration() throws -> Int64
  func getPipelineState() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PipelinePlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `PipelinePlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PipelinePlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startPipelineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.PipelinePlatform.startPipeline\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPipelineChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.startPipeline()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startPipelineChannel.setMessageHandler(nil)
    }
    let stopPipelineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.PipelinePlatform.stopPipeline\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopPipelineChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.stopPipeline()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopPipelineChannel.setMessageHandler(nil)
    }
    let getPipelineGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.PipelinePlatform.getPipelineGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPipelineGenerationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPipelineGeneration()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPipelineGenerationChannel.setMessageHandler(nil)
    }
    let getPipelineStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.PipelinePlatform.getPipelineState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPipelineStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPipelineState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPipelineStateChannel.setMessageHandler(nil)
    }
  }
}
