// Copyright 2026 SoundMesh. All rights reserved.
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum SoundMeshMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionState: Hashable, CustomStringConvertible {
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionState? {
    let state = pigeonVar_list[0] as! String

    return ConnectionState(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: ConnectionState, rhs: ConnectionState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionState")
    SoundMeshMessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "ConnectionState(state: \(String(describing: state)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceInfo: Hashable, CustomStringConvertible {
  var platformName: String
  var osVersion: String
  var deviceModel: String
  var brand: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceInfo? {
    let platformName = pigeonVar_list[0] as! String
    let osVersion = pigeonVar_list[1] as! String
    let deviceModel = pigeonVar_list[2] as! String
    let brand: String? = nilOrValue(pigeonVar_list[3])

    return DeviceInfo(
      platformName: platformName,
      osVersion: osVersion,
      deviceModel: deviceModel,
      brand: brand
    )
  }
  func toList() -> [Any?] {
    return [
      platformName,
      osVersion,
      deviceModel,
      brand,
    ]
  }
  static func == (lhs: DeviceInfo, rhs: DeviceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SoundMeshMessagesPigeonInternal.deepEquals(lhs.platformName, rhs.platformName) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.deviceModel, rhs.deviceModel) && SoundMeshMessagesPigeonInternal.deepEquals(lhs.brand, rhs.brand)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceInfo")
    SoundMeshMessagesPigeonInternal.deepHash(value: platformName, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: deviceModel, hasher: &hasher)
    SoundMeshMessagesPigeonInternal.deepHash(value: brand, hasher: &hasher)
  }

  public var description: String {
    return "DeviceInfo(platformName: \(String(describing: platformName)), osVersion: \(String(describing: osVersion)), deviceModel: \(String(describing: deviceModel)), brand: \(String(describing: brand)))"
  }
}

private class SoundMeshMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ConnectionState.fromList(self.readValue() as! [Any?])
    case 130:
      return DeviceInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SoundMeshMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionState {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SoundMeshMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SoundMeshMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SoundMeshMessagesPigeonCodecWriter(data: data)
  }
}

class SoundMeshMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SoundMeshMessagesPigeonCodec(readerWriter: SoundMeshMessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NetworkHostPlatform {
  func startHosting(port: Int64) throws -> Bool
  func connectToHost(ipAddress: String, port: Int64) throws -> Bool
  func sendMessage(message: String) throws -> Bool
  func disconnect() throws
  func getLocalIpAddress() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NetworkHostPlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `NetworkHostPlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NetworkHostPlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startHostingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.startHosting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startHostingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let portArg = args[0] as! Int64
        do {
          let result = try api.startHosting(port: portArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startHostingChannel.setMessageHandler(nil)
    }
    let connectToHostChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.connectToHost\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectToHostChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ipAddressArg = args[0] as! String
        let portArg = args[1] as! Int64
        do {
          let result = try api.connectToHost(ipAddress: ipAddressArg, port: portArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectToHostChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        do {
          let result = try api.sendMessage(message: messageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        do {
          try api.disconnect()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let getLocalIpAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.NetworkHostPlatform.getLocalIpAddress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocalIpAddressChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLocalIpAddress()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLocalIpAddressChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DevicePlatform {
  func getDeviceInfo() throws -> DeviceInfo
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DevicePlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `DevicePlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DevicePlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.DevicePlatform.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TimingPlatform {
  func getMonotonicTimeNanos() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TimingPlatformSetup {
  static var codec: FlutterStandardMessageCodec { SoundMeshMessagesPigeonCodec.shared }
  /// Sets up an instance of `TimingPlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TimingPlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getMonotonicTimeNanosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.TimingPlatform.getMonotonicTimeNanos\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMonotonicTimeNanosChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMonotonicTimeNanos()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMonotonicTimeNanosChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NetworkFlutterApiProtocol {
  func onMessageReceived(message messageArg: String) async throws
  func onConnectionStateChanged(state stateArg: String) async throws
  func onConnectionError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws
}
class NetworkFlutterApi: NetworkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SoundMeshMessagesPigeonCodec {
    return SoundMeshMessagesPigeonCodec.shared
  }
  func onMessageReceived(message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onMessageReceived\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onConnectionStateChanged(state stateArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onConnectionError(errorCode errorCodeArg: String, errorMessage errorMessageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.soundmesh.NetworkFlutterApi.onConnectionError\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([errorCodeArg, errorMessageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
