// Copyright 2026 SoundMesh. All rights reserved.
// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum TimingMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class TimingMessagesPigeonCodecReader: FlutterStandardReader {
}

private class TimingMessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class TimingMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TimingMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TimingMessagesPigeonCodecWriter(data: data)
  }
}

class TimingMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TimingMessagesPigeonCodec(readerWriter: TimingMessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TimingPlatform {
  func getMonotonicTimeNanos() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TimingPlatformSetup {
  static var codec: FlutterStandardMessageCodec { TimingMessagesPigeonCodec.shared }
  /// Sets up an instance of `TimingPlatform` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TimingPlatform?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getMonotonicTimeNanosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.soundmesh.TimingPlatform.getMonotonicTimeNanos\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMonotonicTimeNanosChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMonotonicTimeNanos()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMonotonicTimeNanosChannel.setMessageHandler(nil)
    }
  }
}
